import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ClientSideMap from '../components/ClientSideMap'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Climy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ClientSideMap />
      </main>
    </div>
  )
}

export default Home
