import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import ClientSideMap from '../components/ClientSideMap'

import "leaflet/dist/leaflet.css"

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Climy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ClientSideMap 
          center={[51.505, -0.09]} 
          zoom={3} 
          minZoom={3}
          maxZoom={12}
          scrollWheelZoom={true} 
        />
      </main>
    </div>
  )
}

export default Home
